version: "3"

services:
  backend:
    build: ./
    container_name: backend
    tty: true
    stdin_open: true
    working_dir: /events
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CQBEvents
      - PORT=3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
  mongodb:
    image: mongo:5.0.7
    container_name: events_db
    restart: always
    ports:
      # Garanta que não haverá conflitos de porta com um mongodb que esteja
      # rodando localmente
      - 27017:27017
networks:
  default:
    name: CQBEvents
